changelog:
  categories:
    - title: Bug Fixes
      labels:
        - bug
    - title: Features
      labels:
        - feature
    - title: Dependencies
      labels:
        - dependency
    - title: Other Changes
      labels:
        - '*'